name: statsfm
description: Official Stats.fm Dart package
version: 0.1.0
homepage: https://github.com/statsfm/statsfm.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  hive_generator: 1.1.2
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.6

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
