name: statsfm
description: Official stats.fm Dart package
version: 1.5.1
homepage: https://github.com/statsfm/statsfm.dart

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  hive_generator: ^2.0.0
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  dio_smart_retry: ^5.0.0
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
